branch-defaults:
  master:
    environment: RSGapp
    group_suffix: null
global:
  application_name: RubyApp
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: us-east-1
  profile: eb-cli
  repository: null
  sc: git
